---
name: "Reviewers action"
author: Yevhen Fabizhevskyi
description: |
  This GitHub action to parse a CODEOWNERS like files and use it to set reviewers
  on PRs.
branding:
  icon: file-text
  color: white
inputs:
  github-token:
    description: "Auth token with permissions to assign reviewers to a PR."
    required: false
    default: "${{ github.token }}"
  pr-number:
    description: "PR number to assign reviewers to."
    required: false
    default: "${{ github.event.pull_request.number }}"
  reviewers-filename:
    description: "CODEOWNERS like filename."
    required: false
    default: "REVIEWERS"
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      env:
        INPUT_GITHUB_TOKEN: "${{ inputs.github-token }}"
        INPUT_PR_NUMBER: "${{ inputs.pr-number }}"
        INPUT_REVIEWERS_FILENAME: "${{ inputs.reviewers-filename }}"
      shell: sh
      run: |
        ./validate-inputs.sh \
          "${INPUT_GITHUB_TOKEN}" \
          "${INPUT_PR_NUMBER}" \
          "${INPUT_REVIEWERS_FILENAME}"
      working-directory: ${{ github.action_path }}/src

    - name: Validate installed tools
      id: tools
      shell: sh
      run: ./validate-installed-tools.sh
      working-directory: ${{ github.action_path }}/src

    - name: Setup curl
      if: steps.tools.outputs.curl == 'false'
      shell: sh
      run: ./install-curl.sh
      working-directory: ${{ github.action_path }}/src

    - name: Setup node
      if: steps.tools.outputs.node == 'false' || steps.tools.outputs.npm == 'false'
      uses: actions/setup-node@v4
      with:
        node-version: "23"

    - name: Install codeowners
      if: steps.tools.outputs.codeowners == 'false'
      shell: sh
      run: npm install -g codeowners

    - name: Get list of changed files
      id: changed-files
      shell: sh
      run: ./get-changed-files.sh "${GITHUB_BASE_REF}" "${GITHUB_HEAD_REF}"
      working-directory: ${{ github.action_path }}/src

    - name: Collect reviewers
      id: reviewers
      env:
        INPUT_REVIEWERS_FILENAME: "${{ inputs.reviewers-filename }}"
      shell: bash
      run: |
        ${{ github.action_path }}/src/get-reviewers.sh \
          "${INPUT_REVIEWERS_FILENAME}" \
          "${{ steps.changed-files.outputs.all }}"

    - name: Assign reviewers
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        INPUT_PR_NUMBER: ${{ inputs.pr-number }}
      shell: sh
      run: |
        ./assign-reviewers.sh \
          "${GITHUB_API_URL}" \
          "${GITHUB_REPOSITORY}" \
          "${GH_TOKEN}" \
          "${INPUT_PR_NUMBER}" \
          '${{ steps.reviewers.outputs.json }}'
      working-directory: ${{ github.action_path }}/src
