---
name: "Reviewers action"
author: Yevhen Fabizhevskyi
description: |
  This GitHub action to parse a CODEOWNERS like files and use it to set reviewers
  on PRs.
branding:
  icon: file-text
  color: white
inputs:
  github-token:
    description: "Auth token with permissions to assign reviewers to a PR."
    required: false
    default: "${{ github.token }}"
  reviewers-filename:
    description: "CODEOWNERS like filename."
    required: false
    default: "REVIEWERS"
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "latest"
    - name: Install codeowners
      shell: sh
      run: npm install -g codeowners
    - name: Get list of changed files
      id: changed-files
      uses: jitterbit/get-changed-files@v1
    - name: Collect reviewers
      id: reviewers
      env:
        INPUT_REVIEWERS_FILENAME: "${{ inputs.reviewers-filename }}"
      shell: bash
      run: |
        ./get-reviewers.sh \
          "${INPUT_REVIEWERS_FILENAME}" \
          "${{ steps.changed-files.outputs.all }}"
      working-directory: ${{ github.action_path }}/src
    - name: Assign to PR
      uses: actions/github-script@v7
      with:
        script: |
          const { reviewers, teamReviewers } =
            JSON.parse('${{ steps.reviewers.outputs.json }}');
          github.rest.pulls.requestReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            reviewers: reviewers,
            team_reviewers: teamReviewers
          });
