---
name: Assign labels

on:
  pull_request:
    types: [opened]

jobs:
  assign-labels:
    name: Assign labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign
        uses: actions/labeler@v5
