---
name: Linting

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-commit
    if: ${{ !startsWith(github.event.pull_request.title, '[automation]') }}
    uses: fabasoad/reusable-workflows/.github/workflows/wf-pre-commit.yml@main
