---
name: Linting

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-commit
    if: ${{ github.event_name == 'push' || !startsWith(github.event.pull_request.title, '[automation]') }}
    uses: fabasoad/reusable-workflows/.github/workflows/wf-pre-commit.yml@main
