---
name: Trigger Functional Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/functional-tests.yml
      - .github/workflows/trigger-functional-tests.yml
      - .github/REVIEWERS
      - src/**
      - action.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/functional-tests.yml
      - .github/workflows/trigger-functional-tests.yml
      - .github/REVIEWERS
      - src/**
      - action.yml

defaults:
  run:
    shell: sh

jobs:
  prepare-pr:
    name: Prepare PR for test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions: {}
    steps:
      - name: Generate GitHub token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: "${{ vars.GH_APP_PR_CRUD_APP_ID }}"
          private-key: "${{ secrets.GH_APP_PR_CRUD_PRIVATE_KEY }}"
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
          persist-credentials: "false"
      - name: Modify files
        run: |
          echo "${GITHUB_RUN_ID}" > ci-tests/test1.txt
          echo "${GITHUB_RUN_ID}" > ci-tests/test2.txt
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          base: ${{ github.head_ref }}
          branch: automation/job-${{ github.run_id }}
          title: "[automation] job #${{ github.run_id }}"
          token: ${{ steps.app-token.outputs.token }}
      - name: Print notice about PR creation
        env:
          CREATE_PR_OUTPUT_PULL_REQUEST_NUMBER: "${{ steps.create-pr.outputs.pull-request-number }}"
          CREATE_PR_OUTPUT_PULL_REQUEST_URL: "${{ steps.create-pr.outputs.pull-request-url }}"
        run: |
          echo "::notice title=PR #${CREATE_PR_OUTPUT_PULL_REQUEST_NUMBER} is created::${CREATE_PR_OUTPUT_PULL_REQUEST_URL}"
      - name: Wait until PR is closed
        uses: actions/github-script@v9
        env:
          CREATE_PR_OUTPUT_PULL_REQUEST_NUMBER: "${{ steps.create-pr.outputs.pull-request-number }}"
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const prNumber = process.env.CREATE_PR_OUTPUT_PULL_REQUEST_NUMBER;
            const sleep = (sec) => new Promise(r => setTimeout(r, sec * 1000));
            while (true) {
              const resp = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
              });
              core.debug('Response:');
              core.debug(resp);
              const expectedState = 'closed';
              const actualState = resp.data.state;
              if (expectedState !== actualState) {
                core.debug(`Expected PR state: ${expectedState}. Actual: ${actualState}`)
                console.log(`⏲ PR #${prNumber} is not closed yet. Sleeping 5 seconds...`)
                await sleep(5);
                continue;
              }
              console.log(`✓ PR #${prNumber} is closed.`)
              break;
            }
      - name: Print notice about PR closing
        env:
          CREATE_PR_OUTPUT_PULL_REQUEST_NUMBER: "${{ steps.create-pr.outputs.pull-request-number }}"
          CREATE_PR_OUTPUT_PULL_REQUEST_URL: "${{ steps.create-pr.outputs.pull-request-url }}"
        run: |
          echo "::notice title=PR #${CREATE_PR_OUTPUT_PULL_REQUEST_NUMBER} is closed::${CREATE_PR_OUTPUT_PULL_REQUEST_URL}"
