---
name: Trigger Functional Tests

on:
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - .github/workflows/trigger-functional-tests.yml
      - .github/REVIEWERS
      - src/**
      - action.yml

defaults:
  run:
    shell: sh

jobs:
  create-pr:
    name: Create PR
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Modify files
        run: |
          echo "${{ github.run_id }}\n" > ci-tests/test1.txt
          echo "${{ github.run_id }}\n" > ci-tests/test2.txt
      - name: Generate GitHub token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_PR_ACCESS_ID }}
          private-key: ${{ secrets.APP_PR_ACCESS_PRIVATE_KEY }}
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          base: ${{ github.head_ref }}
          title: "[automation] job #${{ github.run_id }}"
          token: ${{ steps.app-token.outputs.token }}
      - name: Print PR info
        run: |
          echo "::notice title=PR #${{ steps.create-pr.outputs.pull-request-number }} is created::${{ steps.create-pr.outputs.pull-request-url }}"
